[project]
name = "ml-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.13"
dependencies = [
    "basedpyright>=1.28.0",
    "numpy>=1.24.4",
    "ruff>=0.9.7",
    "scikit-learn>=1.3.2",
]
